### ISSUE TITLE
/click EMAAssistMaster, Promote Master to Party Leader, and Group Disband Problems

### ISSUE THREAD

**Issue by ostill82** [ebonyfaye/ema#124]
I lost all of my configurations, settings, macros, addons, etc., recently. I have now got everything set back up, everything is working but the /click EMAAssistMaster command, Promote Master to Party Leader, and Group Disband key bind. Any suggestions?

**Comment by ebonyfaye** [comment]
It's a blizzard end bug from what I understand

**Comment by ostill82** [comment]
I found this post from July after doing some more digging
https://github.com/Stanzilla/WoWUIBugs/issues/552#issuecomment-2192109095
and this thread from August
https://us.forums.blizzard.com/en/wow/t/click-macros-1100/1910312
It sounds like Blizzard killed the /click command for us

**Comment by ebonyfaye** [comment]
This should be fixed

**Comment by ostill82** [comment]
Hey, sorry to bother you again. It still didn't work for me so I took a break for awhile. Decided to come back and try again, using normal /assist if I have to. The /click EMAAssistMaster and /click EMATargetMaster commands, Promote Master to Party Leader, and Group Disband key bind, are still not working. 
Follow, Stop Follow, and Set Current Character the Master, and Invite Team to Group are all working.

This is on Windows 10, I think I used CurseForge to download EMA. Have been attempting to use the features in Classic Era and Classic Hardcore. Using EMA Version: Release-v4.7(0265).
